```{r, echo=FALSE}
source(file = "include/deadlines.R")
```

# Academic Writing {#04-Writing}

In this chapter, you will learn about different elements of academic writing. We have split this into different components to focus on academic writing, paragraph structure to encourage the use of PEEL paragraphs, and using evidence in your writing. We then have content on APA formatting for which content should follow the stardardised format in the style guide.

## Academic writing

While we encourage you to approach reading journal articles to develop a sense of scientific writing style, they are not always the best examples of how to write well. This means writing for clarity and conciseness, to help communicate your ideas to the reader. 

Some authors approach writing by trying to fill it with as many big words as they can find. We want you to learn the technical terms to use where appropriate, but the writing around them should be clear and concise with effective paragraph structure. [Freeling et al. (2021)](https://www.frontiersin.org/article/10.3389/fpsyg.2021.714321){target="_blank"} showed how writing in a more engaging accessible style results in higher readability, understanding, and confidence in a topic. So, there are a few things to aim for and a few things to avoid in your writing. 

### Aim

- Write precisely and accurately and choose the word/phrase that best expresses your idea.

- Use technical language, with clear definitions where necessary.

- Use short sentences and straightforward sentence structures where possible.

- Write in a clear, accessible style. Remember, the point of scientific writing is to clearly convey information, not to entertain or to show off your vocabulary.

### Try to avoid

- Colloquial or conversational English. 

- Unnecessarily complex language and unnecessary "rhetorical flourishes" such as irony, ambiguity (intentional or otherwise), and informal language.

- Asking rhetorical questions. The purpose of a report or essay is to explain to the reader what something means, not pose a question back at them. 

- Contractions such as ‘can’t’, ‘don’t’ or ‘isn’t’ - always use the full phrase.

### Top Tips to improve your writing

- Do not submit the first draft. No-one ever writes anything good on the first attempt. Good writing is all in the editing process, the first draft is just about getting your ideas on the page. We once saw the advice (but cannot remember the source): "the first draft is explaining your ideas to yourself, the editing is about explaining your ideas to the reader".

- Read your essay out loud as you will easily spot a horrendously long sentence as you lose your breath trying to read it aloud.

- Proof-read after a day or so break. If you are too close to it, you might not spot mistakes or where ideas are not expressed clearly for the naive reader. 

- Ask a friend to proof-read. This is particularly helpful if they do not study psychology (or if they are doing a different topic than you) because they will only understand it if you have properly explained your key concepts and if the logic flows.

- Read lots of journal articles as you will start to recognise what works and what does not work for you as the reader, so you can start to reflect it in your own writing.  

### Further resources

The [Student Learning Development team](https://www.gla.ac.uk/myglasgow/sld/){target="_blank"} have several sources of support available:

- You can book 1-to-1 advice and support sessions.

- There is [additional support available](https://www.gla.ac.uk/myglasgow/sld/about/team/international/){target="_blank"} for international students.

- There are pre-recorded classes in a Moodle course you can self-enrol in.

You are probably busy enough with your degree, but if you want to work on your academic writing, there is an excellent free course on Coursera called [Writing in the Sciences](https://www.coursera.org/learn/sciwrite?){target="_blank"}. This has 8 modules covering concepts like effective writing, verbs, and sentence structure. 

## Paragraph structure 

Once you start organising your ideas into writing, its important to consider good paragraph structure. We recommend learning the PEEL approach to paragraphs: 

- Point – Your topic sentence or two starts the paragraph to outline the key point you are making. Readers should be able to skim through your writing and recognise from the first sentence or two what the point of each paragraph is. 

- Evidence – Once you outlined the point you are making, its time to explain the evidence relating to your point. 

- Explain – Now you have presented the evidence, you need to explain what the evidence means for your overall point. 

- Link – Finally, in the final sentence or two, you have a summary sentence to wrap up your paragraph and help transition to the next paragraph. 

For an example, we will break down a paragraph from [Robertson and Simmons (2013)](https://link.springer.com/article/10.1007/s10803-012-1608-7){target="_blank"}:

> There are a number of neural theories of autism that aim to explain the unusual sensory processing reported within this population. Enhanced Perceptual Functioning (EPF) theory (Mottron, Dawson, Soulières, Hubert, & Burack, 2006) is based on the premise that individuals with ASD exhibit superior local processing abilities. This theory proposes that ASD stems from a superiority of low-level perception (such as discrimination and pattern perception), resulting in  increased attention to lower order cognitive  processes, at the expense of higher order ones (eg social interaction) (Mottron & Burack, 2001). In an update to the Enhanced Perceptual Functioning theory, the  authors  hypothesised that the superior local processing observed in ASD is a result of mandatory global bias in individuals without  ASD, even when it is detrimental to task  performance (Mottron et al., 2006). The ‘neural noise hypothesis’ also provides an account for atypical sensory reactivity reported in ASD. The concept of a ‘noisy system’ has been proposed in multiple studies and reviews (Dakin & Frith, 2005; Franklin et al., 2010; Sanchez-Marin & Padilla-Medina, 2008; Simmons et al., 2009) to explain the performance of individuals with ASD. When combined with the evidence of increased heterogeneity in ASD, particularly that of intraparticipant variability (Milne, 2011), it was proposed that neural noise could account for the strengths and impairments observed in ASD (Simmons et al., 2007).

1. Point

The first sentence outlines the topic of the paragraph. 

> **There are a number of neural theories of autism that aim to explain the unusual sensory processing reported within this population.**

2. Evidence

We then add evidence to support this point. 

> There are a number of neural theories of autism that aim to explain the unusual sensory processing reported within this population. **Enhanced Perceptual Functioning (EPF) theory (Mottron, Dawson, Soulières, Hubert, & Burack, 2006) is based on the premise that individuals with ASD exhibit superior local processing abilities. This theory proposes that ASD stems from a superiority of low-level perception (such as discrimination and pattern perception), resulting in  increased attention to lower order cognitive  processes, at the expense of higher order ones (eg social interaction) (Mottron & Burack, 2001).**

3. Explain 

Once you have outlined the evidence, you need to explain what it means for the point you are making. 

> There are a number of neural theories of autism that aim to explain the unusual sensory processing reported within this population. Enhanced Perceptual Functioning (EPF) theory (Mottron, Dawson, Soulières, Hubert, & Burack, 2006) is based on the premise that individuals with ASD exhibit superior local processing abilities. This theory proposes that ASD stems from a superiority of low-level perception (such as discrimination and pattern perception), resulting in  increased attention to lower order cognitive  processes, at the expense of higher order ones (eg social interaction) (Mottron & Burack, 2001). **In an update to the Enhanced Perceptual Functioning theory, the  authors  hypothesised that the superior local processing observed in ASD is a result of mandatory global bias in individuals without  ASD, even when it is detrimental to task  performance (Mottron et al., 2006). The ‘neural noise hypothesis’ also provides an account for atypical sensory reactivity reported in ASD. The concept of a ‘noisy system’ has been proposed in multiple studies and reviews (Dakin & Frith, 2005; Franklin et al., 2010; Sanchez-Marin & Padilla-Medina, 2008; Simmons et al., 2009) to explain the performance of individuals with ASD.**

4. Link

Finally, once you have explained what the evidence means, it is type to wrap up and help transition to the next paragraph. 

> There are a number of neural theories of autism that aim to explain the unusual sensory processing reported within this population. Enhanced Perceptual Functioning (EPF) theory (Mottron, Dawson, Soulières, Hubert, & Burack, 2006) is based on the premise that individuals with ASD exhibit superior local processing abilities. This theory proposes that ASD stems from a superiority of low-level perception (such as discrimination and pattern perception), resulting in  increased attention to lower order cognitive  processes, at the expense of higher order ones (eg social interaction) (Mottron & Burack, 2001). In an update to the Enhanced Perceptual Functioning theory, the  authors  hypothesised that the superior local processing observed in ASD is a result of mandatory global bias in individuals without  ASD, even when it is detrimental to task  performance (Mottron et al., 2006). The ‘neural noise hypothesis’ also provides an account for atypical sensory reactivity reported in ASD. The concept of a ‘noisy system’ has been proposed in multiple studies and reviews (Dakin & Frith, 2005; Franklin et al., 2010; Sanchez-Marin & Padilla-Medina, 2008; Simmons et al., 2009) to explain the performance of individuals with ASD. **When combined with the evidence of increased heterogeneity in ASD, particularly that of intraparticipant variability (Milne, 2011), it was proposed that neural noise could account for the strengths and impairments observed in ASD (Simmons et al., 2007).**

Developing good paragraph structure is also a key part of the editing process. It's perfectly fine to write as much as you can and get your ideas down on a page. However, you then need to go back, proof-read, and edit to make sure your writing is aligned with the PEEL structure. 

Key things to look out for are questioning whether your paragraph contains one key point. If you cannot summarise your paragraph or you are starting to list everything you are covering, its a sign you might need to break down your paragraph into two, and work on new topic and summary/link sentences. 

Likewise, you might see there is a paragraph with just one or two sentences, with little evidence or explanation. This is a sign you might need to add further writing to develop it into a full PEEL paragraph with topic and summary/link sentences. 

## Using evidence 

Any report you write as a researcher must be evidence-based, otherwise it would be more of an opinion piece. To show what evidence is behind your claims, you must use citations in your report. In this section, we are focusing on the role of citations and how they show what evidence you are using. In the next section on APA formatting, you will learn more about the specific formatting requirements of the citations. 

It’s not enough to have a single citation at the end of a paragraph, or even a list of citations randomly put in. Every fact, point, and evaluation is likely to have come from someone else’s work or something that has influenced your thinking, so you should cite that source. You need to ensure that you cite the evidence you are using to make your point.

Try to put the citation near or next to the point you are making to show where that specific point came from, rather than adding a list of citations at the end and expecting the reader to know which citation relates to each claim. 

Compare these sentences:

1. "Previous research suggests voices can impact our perception of trust (citation), dominance (citation), and attractiveness (citation)" 

2. "Previous research suggests voices can impact our perception of trust, dominance, and attractiveness (citation; citation; citation)" 

The first sentence says each paper tested one individual variable (trust, dominance or attractiveness). The second sentence says all three papers tested all three variables. Both can be true but you need to keep in mind how citation placement changes the understanding.

Citations do not have to go just at the end of a sentence. Use them in different places to create a sense of flow and narrative in your writing. If you only use one style of citation, your writing might be less engaging, so try to switch between **direct** and **indirect** citations. 
For a longer demonstration, we will adapt an extract from the following article:

> Silberzahn, R., Uhlmann, E. L., Martin, D. P., Anselmi, P., Aust, F., Awtrey, E., Bahník, Š., Bai, F., Bannard, C., Bonnier, E., Carlsson, R., Cheung, F., Christensen, G., Clay, R., Craig, M. A., Dalla Rosa, A., Dam, L., Evans, M. H., Flores Cervantes, I., … Nosek, B. A. (2018). Many Analysts, One Data Set: Making Transparent How Variations in Analytic Choices Affect Results. *Advances in Methods and Practices in Psychological Science, 1*(3), 337–356. https://doi.org/10.1177/2515245917747646

Think about how the meaning and clarity of who said what changes with citation placement. If unsure, you want to aim for the first version.

1. Original version with bold added to emphasise cited points (note that their citation format is in APA 6th edition and some citations would be formatted slightly different in the 7th edition):

> “But what if the methodologists are correct? What if scientific results are highly contingent on subjective decisions at the analysis stage? In that case, **the process of certifying a particular result on the basis of an idiosyncratic analytic strategy might be fraught with unrecognized uncertainty (Gelman & Loken, 2014)**, and **research findings might be less trustworthy than they at first appear to be (Cumming, 2014)**. Had the authors made different assumptions, **an entirely different result might have been observed (Babtie, Kirk, & Stumpf, 2014).**” 

2. Edited version with citations moved in the second sentence to add confusion about who says what:

> “But what if the methodologists are correct? What if scientific results are highly contingent on subjective decisions at the analysis stage? In that case, **the process of certifying a particular result on the basis of an idiosyncratic analytic strategy might be fraught with unrecognized uncertainty and research findings might be less trustworthy than they at first appear to be (Cumming, 2014; Gelman & Loken, 2014)**. Had the authors made different assumptions, **an entirely different result might have been observed (Babtie, Kirk, & Stumpf, 2014)**.” 

3. Edited version with all citations moved to the end creating even more confusion as to who said what:

> “But what if the methodologists are correct? What if scientific results are highly contingent on subjective decisions at the analysis stage? In that case, **the process of certifying a particular result on the basis of an idiosyncratic analytic strategy might be fraught with unrecognized uncertainty and research findings might be less trustworthy than they at first appear to be. Had the authors made different assumptions, an entirely different result might have been observed (Babtie, Kirk, & Stumpf, 2014; Cumming, 2014; Gelman & Loken, 2014)**.” 

4. Edited version with no citations which is now just plagiarism when you are not acknowledging the source of information, either intentionally or not:

> “But what if the methodologists are correct? What if scientific results are highly contingent on subjective decisions at the analysis stage? In that case, **the process of certifying a particular result on the basis of an idiosyncratic analytic strategy might be fraught with unrecognized uncertainty and research findings might be less trustworthy than they at first appear to be. Had the authors made different assumptions, an entirely different result might have been observed.**” 

## APA formatting

When you are writing a piece of work and use someone else's ideas or findings, you must reference them and the specific work you are referring to. In psychology, we often use the American Psychological Associations's (APA) reference style (7th edition). APA style also covers other aspects of formatting such as report headings, presenting tables and figures, and numbers, but we will introduce you to that in future weeks. 

You may have used other referencing systems in your previous degree (e.g., Harvard), but it is important you use APA for psychology in your current degree programme. Remember, a reference manager can really help with the heavy lifting here and do a lot of the formatting. But you still need to know APA 7 style well enough to spot when there might be errors. 

There are two things to pay attention to, **in-text citations** and the **reference list**.

### In-text citations 

In-text citations are a short version of the source you are referring to in the main text. Citations include the author's surname and the year of publication.

**Direct citations** include the authors' names as part of the sentence, such as "Karpicke and Roediger (2009) argued...". 

They do not contain first names and they typically do not contain initials (the only time you include initials is when you have two authors with the same surname you want to distinguish). There is no article title as it takes up a lot of words and you will be able to see the title in the reference list. 

For a subtle part of APA style, when two authors are part of the sentence, you use "and" rather than "&" to separate the surnames. 

**Indirect citations** are when you include the authors' names and year of publication within brackets. You are still acknowledging the source of evidence, but the surnames are not part of the sentence, such as "...there may be socio-motivational benefits of attending (French & Kennedy, 2017), or...". 

Indirect citations still do not contain first names nor usually include initials, but this time you use "&" rather than "and" to separate two authors. All the names and year are in parentheses, and there is a comma between the final surname and year. 

There are slightly different formats for citations depending on whether there is one author, two authors, or three or more authors.

- **One author**: Jackman (2017) or (Jackman, 2017)

- **Two authors**: Jackman and Fassbender (2016) or (Jackman & Fassbender, 2016)

- **Three or more authors**: Rolfe et al. (2010) or (Rolfe et al., 2010)

This means you always include all the authors when there are one or two people, but three or more is shortened to first author et al., meaning "and others". 

Sometimes, you will include multiple citations in the same parentheses to show the evidence base behind a given point. If you cite two or more studies, they should be in alphabetical order of the author and separated with a semi-colon, such as "(Phillips et al., 2010; Rolfe et al., 2010)". 

If you have two or more studies from the same authors (in the same author order), then you order by year of publication, giving the author's last names once and adding the date of each subsequent work, such as "(Davies, 2008, 2010, 2012)". 

### Reference lists

A **reference list** is a list of all the sources you cited in your report. In comparison, a **bibliography** is a list of all the sources you consulted while writing your report, even when you do not cite them. 

In psychology, you should only provide a reference list where the references are listed in alphabetical order of the first author's surname. In this course, you **will not** need to provide a bibliography.

As an example, a reference entry should look like this:

> Flake, J. K., & Fried, E. I. (2020). Measurement Schmeasurement: Questionable Measurement Practices and How to Avoid Them. *Advances in Methods and Practices in Psychological Science, 3*(4), 456–465. https://doi.org/10.1177/2515245920952393

You start by listing each author by the last name, a comma, their initial(s), and a full stop. Authors are separated by "&", and after the final author, you include the year of publication in brackets with a full-stop at the end. You have the title of the article which is not in italics. You then have the name of the journal in italics, a comma, and the volume and issue number (in the format "volume number(issue number)"). The issue number is not always available, so you might only include the volume number after the journal name. Finally, you have the page numbers of the article, and DOI (digital object identifier). 

::: {.callout-warning}
The one thing we cannot easily recreate in the chapters here is a final subtle formatting point. In the reference list, each entry has a hanging indent which you can create in Word or Google Docs. For example, see this resource on [how to include a hanging indent in Word](https://columbiacollege-ca.libguides.com/microsoft-word/indentation){target="_blank"}. 
:::

This demonstrated APA referencing for articles with two numbers, but there are two main differences you will come across. 

The first is when you have three or more authors, each author is separated by a comma, then the final two authors are separated by "&", such as:

> Bostyn, D. H., Sevenhant, S., & Roets, A. (2018). Of Mice, Men, and Trolleys: Hypothetical Judgment Versus Real-Life Behavior in Trolley-Style Moral Dilemmas. *Psychological Science, 29(7)*, 1084-1093. https://doi.org/10.1177/0956797617752640

The second is when there are many authors. If there are more than 20 authors, the first 19 are reported, you include an ellipsis (...) to show there is a gap, then you report the final author in the list. For example: 

> Ebersole, C. R., Atherton, O. E., Belanger, A. L., Skulborstad, H. M., Allen, J. M., Banks, J. B., Baranski, E., Bernstein, M. J., Bonfiglio, D. B. V., Boucher, L., Brown, E. R., Budiman, N. I., Cairo, A. H., Capaldi, C. A., Chartier, C. R., Chung, J. M., Cicero, D. C., Coleman, J. A., Conway, J. G., … Nosek, B. A. (2016). Many Labs 3: Evaluating participant pool quality across the academic semester via replication. *Journal of Experimental Social Psychology, 67*, 68–82. https://doi.org/10.1016/j.jesp.2015.10.012

### Further resources

The APA style manual has over 700 pages, so we are not going to cover every type of resource. We have covered journal articles in detail, and the other two sources you will cite most often are books and websites. 

::: {.callout-tip}
#### Try this
If you needed to cite and reference a book or website, how would you do it? Search the APA style resources to check what information you would need to include compared to a journal article. 
:::

There is an APA style website where they have two super useful pages:

1. [Reference examples](https://apastyle.apa.org/style-grammar-guidelines/references/examples){target="_blank"} - This page shows examples of citations and references for different sources. 

2. [The APA style blog](https://apastyle.apa.org/blog){target="_blank"} - The blog is a useful resource as it includes short articles where people ask questions on how they can format and style certain information. This can be useful for new technology or resources as they cover it before a new edition of the full style guide will be released. 
